language: java
sudo: true

services:
  - mysql  

before_install:
  - mysql -e 'CREATE DATABASE searching;'
  - mysql -e 'CREATE USER admin;'
  - mysql -e 'GRANT ALL ON searching.* TO "admin"@"localhost" identified by "fworks";'
  - chmod +x mvnw

jobs:
  include:
  - stage: test
    jdk: oraclejdk10
    #script: mvn -q verify -Pcheck-semantic-version -DskipTests=true
    script: "mvn install"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    
branches:
  only:
  - master
  