language: java

jobs:
  include:
  - stage: test
    jdk: oraclejdk10
    #script: mvn -q verify -Pcheck-semantic-version -DskipTests=true
    script: "mvn cobertura:cobertura"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    
branches:
  only:
  - master