version: "3.2"

services:

  # service-discovery - Eureka
  server-eureka:
    image: fworks/algorithmsboot-eureka
    ports:
      - 8761:8761
    restart: always
    networks:
      - net
    hostname: server-eureka
    container_name: server-eureka
    
  # service admin
  server-admin:
    image: fworks/algorithmsboot-admin
    ports:
      - 9000:9000
    restart: always
    networks:
      - net
    hostname: server-admin
    container_name: server-admin    
    
  # app-algorithms
  app-algorithms:
    image: fworks/algorithmsboot-app
    ports:
      - 8080:8080
    restart: always
    networks:
      - net
    hostname: app-algorithms
    container_name: app-algorithms      

  # searching-service
  searching-service:
    image: fworks/algorithmsboot-searching
    ports:
      - 8081:8080
    restart: always
    networks:
      - net
    hostname: searching-service
    container_name: searching-service          

  # sorting-service
  sorting-service:
    image: fworks/algorithmsboot-sorting
    ports:
      - 8082:8080
    restart: always
    networks:
      - net
    hostname: sorting-service
    container_name: sorting-service          
    
  # problems-service
  problems-service:
    image: fworks/algorithmsboot-problems
    ports:
      - 8083:8080
    restart: always
    networks:
      - net
    hostname: problems-service
    container_name: problems-service          

  # mongo
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    networks:
      - net
    volumes:
      - 'mongodb_data:/data/db'
    hostname: mongodb
    container_name: mongodb
       
  # mysql
  mysql:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=fworks
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=fworks
      - MYSQL_DATABASE=searching
    ports:
      - "3306:3306"
    networks:
      - net
    volumes:
      - 'mysql_data:/var/lib/mysql'
    hostname: mysql
    container_name: mysql   

  # elk
  #elk:
    #image: sebp/elk
    #ports:
     # - "5601:5601"
     # - "9200:9200"
     # - "5044:5044"
    #networks:
     # - net
    #volumes:
     # - 'elk-data:/var/lib/elasticsearch'
    #hostname: elk
    #container_name: elk

networks:
  net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mysql_data:
    driver: local
  elk-data:
    driver: local
    